"""FR-047 (surface version skew) and FR-048 (refresh never touches
user-owned state): a refresh leaves the encrypted configuration, the
machine records, the name pool and the presets byte-identical, and only
overwrites a pristine-tracked file the user has not hand-edited.
"""

from __future__ import annotations

from webui import seed


def _seed_kwargs(paths):
    return {k: v for k, v in paths.items() if k != "inventories_dir"}


def _write(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _make_layout(tmp_path):
    inventories_dir = tmp_path / "inventories"
    state_dir = inventories_dir / ".webui"
    pristine_dir = tmp_path / "pristine"
    image_version_file = tmp_path / "VERSION"

    _write(pristine_dir / "group_vars" / "all" / "vault-template.yml", "template: v1\n")
    _write(pristine_dir / "group_vars" / "hcloud" / "vars.yml", "hcloud_default_location: fsn1\n")

    # First run: the container runtime already copied the image's
    # inventories/ into the empty volume, so it starts out identical.
    _write(
        inventories_dir / "group_vars" / "all" / "vault-template.yml", "template: v1\n"
    )
    _write(
        inventories_dir / "group_vars" / "hcloud" / "vars.yml",
        "hcloud_default_location: fsn1\n",
    )

    image_version_file.write_text("v1\n", encoding="utf-8")

    paths = dict(
        inventories_dir=inventories_dir,
        state_dir=state_dir,
        pristine_dir=pristine_dir,
        image_version_file=image_version_file,
        seeded_version_file=state_dir / "seeded-version",
    )
    return paths


def test_ensure_seeded_records_version_and_manifest_on_first_run(tmp_path):
    paths = _make_layout(tmp_path)
    seed.ensure_seeded(**_seed_kwargs(paths))

    assert seed.seeded_version(paths["seeded_version_file"]) == "v1"
    assert (paths["state_dir"] / "seeded-manifest.json").exists()


def test_ensure_seeded_is_a_noop_on_second_call(tmp_path):
    paths = _make_layout(tmp_path)
    seed.ensure_seeded(**_seed_kwargs(paths))
    manifest_before = (paths["state_dir"] / "seeded-manifest.json").read_text()

    paths["image_version_file"].write_text("v2\n", encoding="utf-8")
    seed.ensure_seeded(**_seed_kwargs(paths))

    assert seed.seeded_version(paths["seeded_version_file"]) == "v1"
    assert (paths["state_dir"] / "seeded-manifest.json").read_text() == manifest_before


def test_needs_defaults_refresh_detects_version_skew(tmp_path):
    paths = _make_layout(tmp_path)
    seed.ensure_seeded(**_seed_kwargs(paths))
    assert not seed.needs_defaults_refresh(
        image_version_file=paths["image_version_file"],
        seeded_version_file=paths["seeded_version_file"],
    )

    paths["image_version_file"].write_text("v2\n", encoding="utf-8")
    assert seed.needs_defaults_refresh(
        image_version_file=paths["image_version_file"],
        seeded_version_file=paths["seeded_version_file"],
    )


def test_refresh_updates_unedited_defaults_and_preserves_user_owned_state(tmp_path):
    paths = _make_layout(tmp_path)
    seed.ensure_seeded(**_seed_kwargs(paths))

    # User-owned state that must survive a refresh untouched (FR-048).
    vault_file = paths["inventories_dir"] / "group_vars" / "all" / "vault.yml"
    _write(vault_file, "ENCRYPTED-CONTENT-UNCHANGED\n")
    autogen_file = paths["inventories_dir"] / "hcloud_autogenerated.yml"
    _write(autogen_file, "all:\n  hosts: {edoras: {}}\n")
    pool_file = paths["state_dir"] / "hostname_pool_hcloud.yml"
    _write(pool_file, "hostname_pool:\n  - edoras\n")
    presets_file = paths["state_dir"] / "presets.json"
    _write(presets_file, "[]\n")

    vault_before = vault_file.read_bytes()
    autogen_before = autogen_file.read_bytes()
    pool_before = pool_file.read_bytes()
    presets_before = presets_file.read_bytes()

    # New image: the template gained new content.
    _write(paths["pristine_dir"] / "group_vars" / "all" / "vault-template.yml", "template: v2\n")
    paths["image_version_file"].write_text("v2\n", encoding="utf-8")

    result = seed.refresh_defaults(**paths)

    assert "group_vars/all/vault-template.yml" in result.updated
    assert (
        paths["inventories_dir"] / "group_vars" / "all" / "vault-template.yml"
    ).read_text() == "template: v2\n"
    assert seed.seeded_version(paths["seeded_version_file"]) == "v2"

    assert vault_file.read_bytes() == vault_before
    assert autogen_file.read_bytes() == autogen_before
    assert pool_file.read_bytes() == pool_before
    assert presets_file.read_bytes() == presets_before


def test_refresh_skips_a_file_the_user_hand_edited(tmp_path):
    paths = _make_layout(tmp_path)
    seed.ensure_seeded(**_seed_kwargs(paths))

    volume_vars_file = paths["inventories_dir"] / "group_vars" / "hcloud" / "vars.yml"
    _write(volume_vars_file, "hcloud_default_location: hand-edited\n")

    _write(
        paths["pristine_dir"] / "group_vars" / "hcloud" / "vars.yml",
        "hcloud_default_location: nbg1\n",
    )
    paths["image_version_file"].write_text("v2\n", encoding="utf-8")

    result = seed.refresh_defaults(**paths)

    assert "group_vars/hcloud/vars.yml" in result.skipped_edited
    assert volume_vars_file.read_text() == "hcloud_default_location: hand-edited\n"
