#!/bin/bash
# Entrypoint for the ansible-runner image.
#
# Contract:
#   - PLAYBOOK (env, required): repo-relative playbook path, e.g.
#     playbooks/create-vm.yml
#   - All further CLI arguments are passed through to ansible-playbook
#     (--extra-vars, --tags, --check, ...).
#
# Secrets are never baked into the image; they are host-mounted at runtime.
# See .docker/README.md for the full mount and environment variable tables.
set -euo pipefail

# IMAGE_REF and SOURCE_REPO are baked in by the Dockerfile from build args
# that CI fills from the publishing repository. Both are empty for a local
# build, which has no published counterpart to point at.
# Untagged: every use below appends the tag itself.
IMAGE_REF="${IMAGE_REF:-ansible-runner}"

# Compare the baked VERSION against the latest GitHub release. Completely
# silent on any failure (network, non-200, malformed JSON) — an update
# notice is a convenience, never a blocker.
version_check() {
    local local_version latest repo_api
    # No source repository baked in: locally built image, nothing to compare
    # against. Never guess a repository — a wrong one reports another
    # project's releases as if they were this image's.
    [ -z "${SOURCE_REPO:-}" ] && return 0
    repo_api="https://api.github.com/repos/${SOURCE_REPO}/releases/latest"

    local_version=$(cat /ansible/VERSION 2>/dev/null) || return 0
    [ -z "${local_version}" ] && return 0
    [ "${local_version}" = "dev" ] && return 0

    latest=$(python3 - "${repo_api}" <<'PYEOF' 2>/dev/null
import json
import sys
import urllib.request

try:
    with urllib.request.urlopen(sys.argv[1], timeout=3) as response:
        tag = json.load(response)["tag_name"]
    if tag:
        print(tag)
except Exception:
    pass
PYEOF
    ) || return 0

    if [ -n "${latest}" ] && [ "${latest}" != "${local_version}" ]; then
        echo "NOTICE: image version ${local_version}, latest release ${latest}."
        echo "        Update with: docker pull ${IMAGE_REF}:latest"
        echo ""
    fi
    return 0
}

# Warn about missing mounts/variables without failing: the playbook that
# actually needs them will fail loudly on its own (constitution
# principle XII applies to the plays, not to this dispatcher).
sanity_checks() {
    if [ ! -f /ansible/inventories/group_vars/all/vault.yml ]; then
        echo "WARNING: /ansible/inventories/group_vars/all/vault.yml not found."
        echo "         Mount your inventories directory (vault secrets AND local"
        echo "         state: autogenerated inventories, known_hosts):"
        echo "           -v /path/to/your/inventories:/ansible/inventories"
        echo ""
    fi

    if ! ls /root/.ssh/* >/dev/null 2>&1; then
        echo "WARNING: no SSH key found in /root/.ssh."
        echo "         Mount your private key read-only, e.g.:"
        echo "           -v ~/.ssh/id_ansible_ed25519:/root/.ssh/id_ansible_ed25519:ro"
        echo "         and pass it to ansible-playbook with:"
        echo "           --private-key /root/.ssh/id_ansible_ed25519"
        echo ""
    fi

    if [ -z "${ANSIBLE_VAULT_PASSWORD:-}" ]; then
        echo "WARNING: ANSIBLE_VAULT_PASSWORD is not set. Vaulted variables"
        echo "         cannot be decrypted. Pass it with:"
        echo "           -e ANSIBLE_VAULT_PASSWORD"
        echo ""
    fi
}

usage() {
    cat <<USAGEEOF
Usage: set the PLAYBOOK environment variable to a repo-relative playbook
path and pass any extra ansible-playbook arguments after the image name.

Example:

  docker run --rm \\
    -v /path/to/your/inventories:/ansible/inventories \\
    -v ~/.ssh/id_ansible_ed25519:/root/.ssh/id_ansible_ed25519:ro \\
    -e ANSIBLE_VAULT_PASSWORD \\
    -e HCLOUD_TOKEN \\
    -e PLAYBOOK=playbooks/create-vm.yml \\
    ${IMAGE_REF}:latest \\
    --extra-vars provider=hcloud --private-key /root/.ssh/id_ansible_ed25519

Available playbooks:
USAGEEOF
    find /ansible -maxdepth 1 -name '*.yml' \
        ! -name 'requirements.yml' -printf '  %f\n' | sort
    find /ansible/playbooks -maxdepth 1 -name '*.yml' \
        -printf '  playbooks/%f\n' | sort
}

version_check
sanity_checks

if [ -z "${PLAYBOOK:-}" ]; then
    usage
    exit 1
fi

echo "Running: ansible-playbook ${PLAYBOOK} $*"
exec ansible-playbook "/ansible/${PLAYBOOK}" "$@"
