"""Paths and defaults for the web frontend.

Every path here is either baked into the image or lives inside the single
mounted volume at ``inventories/``. See specs/017-hcloud-web-frontend/
data-model.md for the storage-tier table this mirrors.
"""

from __future__ import annotations

import os
from pathlib import Path

# Baked into the image (.docker/Dockerfile.web WORKDIR).
ANSIBLE_ROOT = Path(os.environ.get("WEBUI_ANSIBLE_ROOT", "/ansible"))

# The single named volume. Everything the user owns lives under here.
INVENTORIES_DIR = ANSIBLE_ROOT / "inventories"

# Hidden directory holding application state, inside the inventory
# directory Ansible itself scans. Confirmed safe in research.md section 7:
# Ansible skips dot-directories when parsing an inventory directory.
STATE_DIR = INVENTORIES_DIR / ".webui"

SSH_KEY_DIR = STATE_DIR / "ssh"
SSH_PRIVATE_KEY_FILE = SSH_KEY_DIR / "id_ed25519"
SSH_PUBLIC_KEY_FILE = SSH_KEY_DIR / "id_ed25519.pub"

# vault_my_ssh_key_name is a managed field (FR-019: not hand-editable
# through the configuration form), so the interface -- not the user --
# decides what name to register the key under. A distinctive default
# avoids colliding with an unrelated key the user already has in their
# Hetzner account under a generic name like "id_ed25519".
DEFAULT_SSH_KEY_NAME = "ansible-web-frontend"

POOL_FILE = STATE_DIR / "hostname_pool_hcloud.yml"
PRESETS_FILE = STATE_DIR / "presets.json"
SEEDED_VERSION_FILE = STATE_DIR / "seeded-version"

# Server type and location per machine, keyed by hostname. Not part of
# hcloud_autogenerated.yml's schema (that file only ever recorded what an
# SSH connection needs), so the interface tracks these two extra display
# fields itself: written by webui/runner.py when a provisioning run
# succeeds, pruned when a destroy run succeeds. A machine created from the
# command line, outside the interface, simply has no entry here.
MACHINE_DETAILS_FILE = STATE_DIR / "machine_details.json"

# The cost ledger (webui/costs.py): one row per life of a machine, so the
# month's estimate can include machines that no longer exist. SQLite rather
# than a service, for the reasons in that module's docstring; it lives in
# the volume, so it survives a restart and an image upgrade like everything
# else the operator owns.
COST_DB_FILE = STATE_DIR / "costs.sqlite3"

# Repository defaults, baked into the image, read-only at runtime.
DEFAULT_POOL_FILE = ANSIBLE_ROOT / "playbooks" / "vars" / "hostname_pool_hcloud.yml"
VAULT_TEMPLATE_FILE = INVENTORIES_DIR / "group_vars" / "all" / "vault-template.yml"
HCLOUD_VARS_FILE = INVENTORIES_DIR / "group_vars" / "hcloud" / "vars.yml"
HCLOUD_LINUX_VARS_FILE = INVENTORIES_DIR / "group_vars" / "hcloud_linux" / "vars.yml"

# A pristine copy of the volume's starting contents, baked at build time,
# used to detect and refresh stale defaults after an image upgrade
# (research.md section 6, FR-047, FR-048).
PRISTINE_DEFAULTS_DIR = ANSIBLE_ROOT / ".inventories-pristine"
IMAGE_VERSION_FILE = ANSIBLE_ROOT / "VERSION"

# Volume state the interface reads but never writes.
VAULT_FILE = INVENTORIES_DIR / "group_vars" / "all" / "vault.yml"
AUTOGEN_INVENTORY_FILE = INVENTORIES_DIR / "hcloud_autogenerated.yml"
KNOWN_HOSTS_FILE = INVENTORIES_DIR / "hcloud_known_hosts"

# Same script ansible.cfg's vault_password_file points every
# ansible-playbook invocation at; webui/vault.py passes it to the
# standalone ansible-vault binary explicitly rather than relying on
# ansible.cfg discovery, so vault reads/writes don't depend on cwd.
VAULT_PASSWORD_SCRIPT = ANSIBLE_ROOT / "scripts" / "echo-vault-password-environment-variable.sh"

# Playbooks this feature drives, unmodified (plan.md "Modified existing
# files" lists the one exception: playbooks/tasks/create/hcloud.yml).
CREATE_VM_PLAYBOOK = ANSIBLE_ROOT / "playbooks" / "create-vm.yml"
CONFIGURE_PROFILE_PLAYBOOK = ANSIBLE_ROOT / "playbooks" / "configure-profile.yml"
DESTROY_VM_PLAYBOOK = ANSIBLE_ROOT / "playbooks" / "destroy-vm.yml"

# Session secrets: discarded after this many seconds of inactivity, on top
# of being discarded on process stop (spec.md Assumptions).
INACTIVITY_TIMEOUT_SECONDS = 30 * 60

# FR-049: local machine only by default. Binding the process itself to
# 127.0.0.1 inside the container would make the container-runtime port
# mapping unreachable, so loopback-only exposure is enforced by the
# compose files publishing the port to 127.0.0.1 on the host (see
# compose.yaml, compose.build.yaml) rather than by this bind address.
DEFAULT_BIND_HOST = os.environ.get("WEBUI_HOST", "0.0.0.0")  # noqa: S104 - see comment above
DEFAULT_BIND_PORT = int(os.environ.get("WEBUI_PORT", "8080"))

# Bounded ring buffer size for run output (research.md section 9).
RUN_OUTPUT_BUFFER_LINES = 2000

PROFILES = {
    "basic": "A headless development machine: shell tooling and no graphical environment.",
    "desktop": "Everything in basic, plus a graphical desktop environment.",
}

# vCPU, memory, disk and monthly cost sourced from the comment table in
# inventories/group_vars/hcloud_linux/vars.yml, kept here as the single
# place the create form reads sizing detail from (FR-028). Update both
# together if Hetzner's pricing changes.
SERVER_TYPES = {
    "cx23": {"vcpu": 2, "memory_gb": 4, "disk_gb": 40, "monthly_eur": 6.53},
    "cx33": {"vcpu": 4, "memory_gb": 8, "disk_gb": 80, "monthly_eur": 10.10},
    "cx43": {"vcpu": 8, "memory_gb": 16, "disk_gb": 160, "monthly_eur": 19.03},
}

# Sourced from the comment table in inventories/group_vars/hcloud/vars.yml.
LOCATIONS = {
    "hel1": "Helsinki, Finland",
    "fsn1": "Falkenstein, Germany",
    "nbg1": "Nuremberg, Germany",
    "ash": "Ashburn, Virginia, USA",
    "hil": "Hillsboro, Oregon, USA",
    "sin": "Singapore",
}

# spec.md Assumptions: a short curated Ubuntu LTS list is the default,
# shown before any live Hetzner lookup; a toggle on the create page
# switches to the live catalogue for users who want more choice. The
# first entry here is the page's default selection.
UBUNTU_LTS_IMAGES = [
    {"value": "ubuntu-26.04", "label": "Ubuntu 26.04 LTS", "support_end": "2031-04"},
    {"value": "ubuntu-24.04", "label": "Ubuntu 24.04 LTS", "support_end": "2029-04"},
    {"value": "ubuntu-22.04", "label": "Ubuntu 22.04 LTS", "support_end": "2027-04"},
]
