"""Machine records: read hcloud_autogenerated.yml, the file the playbooks
own (create-vm.yml and destroy-vm.yml write it; this module never writes
that file -- data-model.md's Machine Record entity).

Server size, location and image are not part of that file's schema -- it
only ever recorded what an SSH connection needs. They are tracked
separately in config.MACHINE_DETAILS_FILE, written by record_choices()
below when the interface starts a provisioning run. A machine that
predates the interface (created from the command line) has no entry there
and reports them as None rather than guessing -- so when the API token is
unlocked the dashboard overlays what the account itself says, through
merge_account_detail below.

The record holds one thing the account can never answer: which catalogue
each choice was made against. Hetzner reports that a machine is a `cx23`
in `hel1`; it cannot say whether the operator picked that from the
built-in list or from the full live one. A preset made from the machine
has to record the same catalogue the machine was ordered from, or loading
it would show a different list than the one those choices came from.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, replace
from datetime import datetime
from pathlib import Path

import yaml

from . import config, pricing

_PROFILE_GROUPS = ("basic", "desktop")


@dataclass
class Machine:
    name: str
    address: str | None
    profile: str | None
    server_type: str | None
    location: str | None
    # Filled in from the Hetzner account when the API token is unlocked
    # (webui/app.py _machines_with_account_detail). None means nobody has
    # asked the account, not that the machine is off.
    status: str | None = None
    # When the account says the machine was created, and what it charges
    # for it there. Together these are everything a cost needs; without
    # them the interface says "unknown" rather than estimating from a
    # guessed start (webui/pricing.py).
    created_at: datetime | None = None
    rates: pricing.Rates = field(default=pricing.NO_RATES)
    # What the machine was built from, as the account reports it. Nothing
    # local records this -- the image is a create-time choice the machine
    # record never kept -- so it is None until the account is asked, and
    # it is the one field of a preset that can only come from there.
    image: str | None = None


def merge_account_detail(machines: list[Machine], servers: list[dict]) -> list[Machine]:
    """Overlay what the account says about each machine.

    The account is the authority on size, location, address and power
    state; the local records are the authority on which machines this
    installation manages and which profile each was given, which Hetzner
    knows nothing about. So this fills gaps and corrects drift without
    adding or removing rows: a server in the account that this
    installation does not manage is not its business.
    """
    by_name = {server.get("name"): server for server in servers}
    merged = []
    for machine in machines:
        server = by_name.get(machine.name)
        if server is None:
            merged.append(machine)
            continue
        location = _location_of(server) or machine.location
        merged.append(
            replace(
                machine,
                address=_address_of(server) or machine.address,
                server_type=_name_of(server.get("server_type")) or machine.server_type,
                location=location,
                status=server.get("status"),
                created_at=pricing.parse_timestamp(server.get("created")),
                rates=pricing.rates_for(server.get("server_type"), location),
                # The recorded choice wins: it is the reference that was
                # actually ordered, which is what a preset has to repeat.
                # The account's answer fills the gap for a machine this
                # interface did not provision.
                image=machine.image or _image_of(server),
            )
        )
    return merged


def _name_of(value: object) -> str | None:
    """A field the account reports either as an object with a name or, in
    some responses, as the name itself."""
    if isinstance(value, dict):
        name = value.get("name")
        return name if isinstance(name, str) else None
    return value if isinstance(value, str) else None


def _image_of(server: dict) -> str | None:
    """What the server was built from, named the way the create form names
    it.

    A system image answers with a name (`ubuntu-26.04`), which is exactly
    what `image:` takes. A snapshot has no name at all, only a
    description, and its description is not a reference anything can
    provision from -- so it reads as unknown rather than as a name that
    would fail later.
    """
    image = server.get("image")
    if not isinstance(image, dict):
        return _name_of(image)
    name = image.get("name")
    return name if isinstance(name, str) and name else None


def _location_of(server: dict) -> str | None:
    """The location code, wherever this response happens to carry it.

    GET /servers answers with the location at the top level and no
    datacenter key at all, which is where this reads it from. The
    documented datacenter.location.name is read too, and a datacenter with
    no location block still answers with its own name ("nbg1-dc3") --
    which names the right place, and is a better answer than "unknown".
    """
    datacenter = server.get("datacenter")
    for candidate in (
        server.get("location"),
        (datacenter or {}).get("location") if isinstance(datacenter, dict) else None,
    ):
        name = _name_of(candidate)
        if name:
            return name
    return _name_of(datacenter)


def _address_of(server: dict) -> str | None:
    public_net = server.get("public_net") or {}
    ipv4 = public_net.get("ipv4")
    if isinstance(ipv4, dict) and ipv4.get("ip"):
        return ipv4["ip"]
    # A machine reachable over IPv6 only still has an address worth showing.
    ipv6 = public_net.get("ipv6")
    if isinstance(ipv6, dict) and ipv6.get("ip"):
        return ipv6["ip"]
    return None


def _load_details(details_file: Path) -> dict[str, dict]:
    try:
        return json.loads(details_file.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return {}


def record_choices(
    name: str,
    choices: dict,
    *,
    details_file: Path = config.MACHINE_DETAILS_FILE,
) -> None:
    """Write down what this machine was ordered as.

    Written when the run starts rather than when it succeeds: the name is
    claimed from the pool before Hetzner is contacted, and a record for a
    machine that never came up is harmless -- list_machines() only reads
    an entry for a name the playbooks actually put in the inventory, and
    the next machine to take that name overwrites it.
    """
    details = _load_details(details_file)
    details[name] = choices
    details_file.parent.mkdir(parents=True, exist_ok=True)
    details_file.write_text(
        json.dumps(details, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def recorded_choices(
    name: str, *, details_file: Path = config.MACHINE_DETAILS_FILE
) -> dict:
    """What this machine was ordered as, or {} for one this interface did
    not provision."""
    return _load_details(details_file).get(name) or {}


def list_machines(
    *,
    autogen_inventory_file: Path = config.AUTOGEN_INVENTORY_FILE,
    details_file: Path = config.MACHINE_DETAILS_FILE,
) -> list[Machine]:
    try:
        raw = yaml.safe_load(autogen_inventory_file.read_text(encoding="utf-8")) or {}
    except FileNotFoundError:
        return []

    hosts = (raw.get("all") or {}).get("hosts") or {}
    details = _load_details(details_file)

    machines = []
    for name, hostvars in hosts.items():
        profile = next(
            (
                group
                for group in _PROFILE_GROUPS
                if name in ((raw.get(group) or {}).get("hosts") or {})
            ),
            None,
        )
        entry = details.get(name) or {}
        machines.append(
            Machine(
                name=name,
                address=(hostvars or {}).get("ansible_host"),
                profile=profile or entry.get("profile"),
                server_type=entry.get("server_type"),
                location=entry.get("location"),
                image=entry.get("image"),
            )
        )
    return sorted(machines, key=lambda machine: machine.name)


def machine_names(*, autogen_inventory_file: Path = config.AUTOGEN_INVENTORY_FILE) -> set[str]:
    return {machine.name for machine in list_machines(autogen_inventory_file=autogen_inventory_file)}
