"""Machine records: read hcloud_autogenerated.yml, the file the playbooks
own (create-vm.yml and destroy-vm.yml write it; this module never writes
it -- data-model.md's Machine Record entity).

Server size and location are not part of that file's schema -- it only
ever recorded what an SSH connection needs. They are tracked separately in
config.MACHINE_DETAILS_FILE, written by webui/runner.py when a
provisioning run succeeds and pruned when a destroy run succeeds. A
machine that predates the interface (created from the command line) has
no entry there and would report size/location as None rather than
guessing -- so when the API token is unlocked the dashboard overlays what
the account itself says, through merge_account_detail below.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, replace
from pathlib import Path

import yaml

from . import config

_PROFILE_GROUPS = ("basic", "desktop")


@dataclass
class Machine:
    name: str
    address: str | None
    profile: str | None
    server_type: str | None
    location: str | None
    # Filled in from the Hetzner account when the API token is unlocked
    # (webui/app.py _machines_with_account_detail). None means nobody has
    # asked the account, not that the machine is off.
    status: str | None = None


def merge_account_detail(machines: list[Machine], servers: list[dict]) -> list[Machine]:
    """Overlay what the account says about each machine.

    The account is the authority on size, location, address and power
    state; the local records are the authority on which machines this
    installation manages and which profile each was given, which Hetzner
    knows nothing about. So this fills gaps and corrects drift without
    adding or removing rows: a server in the account that this
    installation does not manage is not its business.
    """
    by_name = {server.get("name"): server for server in servers}
    merged = []
    for machine in machines:
        server = by_name.get(machine.name)
        if server is None:
            merged.append(machine)
            continue
        datacenter = server.get("datacenter") or {}
        public_net = server.get("public_net") or {}
        merged.append(
            replace(
                machine,
                address=(public_net.get("ipv4") or {}).get("ip") or machine.address,
                server_type=(server.get("server_type") or {}).get("name") or machine.server_type,
                location=(datacenter.get("location") or {}).get("name") or machine.location,
                status=server.get("status"),
            )
        )
    return merged


def _load_details(details_file: Path) -> dict[str, dict[str, str]]:
    try:
        return json.loads(details_file.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return {}


def list_machines(
    *,
    autogen_inventory_file: Path = config.AUTOGEN_INVENTORY_FILE,
    details_file: Path = config.MACHINE_DETAILS_FILE,
) -> list[Machine]:
    try:
        raw = yaml.safe_load(autogen_inventory_file.read_text(encoding="utf-8")) or {}
    except FileNotFoundError:
        return []

    hosts = (raw.get("all") or {}).get("hosts") or {}
    details = _load_details(details_file)

    machines = []
    for name, hostvars in hosts.items():
        profile = next(
            (
                group
                for group in _PROFILE_GROUPS
                if name in ((raw.get(group) or {}).get("hosts") or {})
            ),
            None,
        )
        entry = details.get(name, {})
        machines.append(
            Machine(
                name=name,
                address=(hostvars or {}).get("ansible_host"),
                profile=profile,
                server_type=entry.get("server_type"),
                location=entry.get("location"),
            )
        )
    return sorted(machines, key=lambda machine: machine.name)


def machine_names(*, autogen_inventory_file: Path = config.AUTOGEN_INVENTORY_FILE) -> set[str]:
    return {machine.name for machine in list_machines(autogen_inventory_file=autogen_inventory_file)}
